### ISSUE TITLE
WPgraphql wont load schema's after enabling this plugin

### ISSUE THREAD

**Issue by ifoi** [DalkMania/wp-graphql-cpt#4] opened 2022-10-31 02:00 UTC
I am experiencing the same issues as   #2 and #1    With WPgraphql cpt Enabled.
Wpgraphql does not show any schema,  it just has a never ending "loading screen" 

i have the following graphql plugins .. 

- WpGraphql Version 1.12.0
-   WpGraphql CORS ver 2.1
- WPGraphQL WooCommerce (WooGraphql)  Version 0.11.2

**Comment by DalkMania** [comment] 2022-11-01 18:10
Hey @ifoi .. I cannot reproduce this behavior. Also which plugin is `WPGraphQL Version 0.11.2` ? 

Are there any logs or anything?

**Comment by ifoi** [comment] 2022-11-04 06:28
oops. the last one should have been WPGrapql WooCommerce (WooGraphql)  version 0.11.2
  i have edited the original post to correct that ..   
  
  I am gonna see if i can get any logs ( i am currently running that site on[ tastewp](https://tastewp.com/r/RB9OqiHel) ) ..   I also noticed that i got the same exact result when i tried another plugin that is supposed to do a similar function as yours.

**Comment by ifoi** [comment] 2022-11-04 06:42
here are the logs .. 


#0 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Type/ObjectType/RootQuery.php(857): WPGraphQL::get_allowed_taxonomies()
#1 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(280): WPGraphQL\Type\ObjectType\RootQuery::register_term_object_fields()
#2 /s2-bansongs/wordpress/wp-includes/class-wp-hook.php(307): WPGraphQL\Registry\TypeRegistry->init_type_registry()
#3 /s2-bansongs/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /s2-bansongs/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(232): do_action()
#6 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry in /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/WPGraphQL.php on line 714
[31-Oct-2022 00:59:06 UTC] PHP Fatal error:  Uncaught GraphQL\Error\UserError: The link_library_category taxonomy isn't configured properly to show in GraphQL. It needs a "graphql_single_name" and a "graphql_plural_name" in /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/WPGraphQL.php:714
Stack trace:
#0 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Type/ObjectType/RootQuery.php(857): WPGraphQL::get_allowed_taxonomies()
#1 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(280): WPGraphQL\Type\ObjectType\RootQuery::register_term_object_fields()
#2 /s2-bansongs/wordpress/wp-includes/class-wp-hook.php(307): WPGraphQL\Registry\TypeRegistry->init_type_registry()
#3 /s2-bansongs/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /s2-bansongs/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(232): do_action()
#6 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry in /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/WPGraphQL.php on line 714
[31-Oct-2022 02:05:44 UTC] PHP Fatal error:  Uncaught GraphQL\Error\UserError: The wp_global_styles post_type isn't configured properly to show in GraphQL. It needs a "graphql_single_name" and a "graphql_plural_name" in /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/WPGraphQL.php:624
Stack trace:
#0 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Type/ObjectType/RootQuery.php(652): WPGraphQL::get_allowed_post_types()
#1 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(279): WPGraphQL\Type\ObjectType\RootQuery::register_post_object_fields()
#2 /s2-bansongs/wordpress/wp-includes/class-wp-hook.php(307): WPGraphQL\Registry\TypeRegistry->init_type_registry()
#3 /s2-bansongs/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /s2-bansongs/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(232): do_action()
#6 /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php in /s2-bansongs/wordpress/wp-content/plugins/wp-graphql/src/WPGraphQL.php on line 624

**Comment by DalkMania** [comment] 2022-11-04 19:56
Thanks @ifoi . 

I took a look at this. According to my testing, I seem to have fixed the issue. I have committed the changes and updated the README. 

Seems like in the log your taxonomy `link_library_category` doesn't have all the keys and values required so try to add `singular_name` to the labels array for that taxonomy. And makes sure all your `custom` taxonomies & post types have it and that it's set to something. 

Please let me know if the new version, fixes your problem. Thanks for reporting.

**Closed as completed by DalkMania** 2022-11-04 19:56 UTC
